apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: rahasak-elasticsearch
spec:
  version: 7.6.2
  nodeSets:
  - name: master
    count: 3
    config:
      node.master: true
      node.data: true
      node.ingest: false
      xpack.ml.enabled: true
      node.store.allow_mmap: false
  - name: data
    count: 7
    config:
      node.master: false
      node.data: true
      node.ingest: false
      xpack.ml.enabled: true
      node.store.allow_mmap: false
  - name: client
    count: 7
    config:
      node.master: false
      node.data: false
      node.ingest: true
      xpack.ml.enabled: true
      node.store.allow_mmap: false
