kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: arnoldas-rolebinding
subjects:
- kind: Group
  name: cn=arnoldas,ou=People,dc=xcitedb,dc=asrc,dc=albany,dc=edu
roleRef:
  kind: ClusterRole
  name: arnoldas-access-role
  apiGroup: rbac.authorization.k8s.io