kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: coe-rolebinding-ldap
subjects:
- kind: Group
  name: /coe
roleRef:
  kind: ClusterRole
  name: coe-access-role
  apiGroup: rbac.authorization.k8s.io