apiVersion: batch/v1
kind: CronJob
metadata:
  name: download-hrrr-00
  namespace: arnoldas
  labels:
    app: download-hrrr-00
spec:
  schedule: "0 1 * * *"            ## Defined schedule using the *nix style cron syntax
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: download-hrrr-00
        spec:
          containers:
          - name: download-hrrr-00
            image:  akurbanovas/cron_lg:0.4
            volumeMounts:
            - name: dcflash-storage-lg
              mountPath: /home/lgaudet
            - name: dcflash-data
              mountPath: /home/lgaudet/model-data
            command: ["/bin/bash"]
            args: ["-c", "/opt/conda/envs/data_pipeline/bin/python /home/lgaudet/AI2ES/Notebooks/single_file_pipeline/s3_download_pipeline.py -m 'hrrr' -p 'wrfsfc' -d $(date +%Y%m%d) -i '00'"]
          volumes:
          - name: dcflash-storage-lg
            hostPath:
              path: /rdma/flash/hulk/raid/lgaudet
          - name: dcflash-data
            hostPath:
              path: /rdma/flash/AI2ES/data
          restartPolicy: OnFailure    ##  Restart Policy in case container failed
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: concat-hrrr-00
  namespace: arnoldas
  labels:
    app: concat-hrrr-00
spec:
  schedule: "30 1 * * *"            ## Defined schedule using the *nix style cron syntax
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: concat-hrrr-00
        spec:
          containers:
          - name: concat-hrrr-00
            image:  akurbanovas/cron_lg:0.4
            volumeMounts:
            - name: dcflash-storage-lg
              mountPath: /home/lgaudet
            - name: dcflash-data
              mountPath: /home/lgaudet/model-data
            command: ["/bin/bash"]
            args: ["-c", "/opt/conda/envs/data_pipeline/bin/python /home/lgaudet/AI2ES/Notebooks/single_file_pipeline/concat_files_fix_precip.py -m 'hrrr' -p 'wrfsfc' -d $(date +%Y%m%d) -i '00'"]
          volumes:
          - name: dcflash-storage-lg
            hostPath:
              path: /rdma/flash/hulk/raid/lgaudet
          - name: dcflash-data
            hostPath:
              path: /rdma/flash/AI2ES/data
          restartPolicy: OnFailure    ##  Restart Policy in case container failed
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: download-hrrr-12
  namespace: arnoldas
  labels:
    app: download-hrrr-12
spec:
  schedule: "0 13 * * *"            ## Defined schedule using the *nix style cron syntax
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: download-hrrr-12
        spec:
          containers:
          - name: download-hrrr-12
            image:  akurbanovas/cron_lg:0.4
            volumeMounts:
            - name: dcflash-storage-lg
              mountPath: /home/lgaudet
            - name: dcflash-data
              mountPath: /home/lgaudet/model-data
            command: ["/bin/bash"]
            args: ["-c", "/opt/conda/envs/data_pipeline/bin/python /home/lgaudet/AI2ES/Notebooks/single_file_pipeline/s3_download_pipeline.py -m 'hrrr' -p 'wrfsfc' -d $(date +%Y%m%d) -i '12'"]
          volumes:
          - name: dcflash-storage-lg
            hostPath:
              path: /rdma/flash/hulk/raid/lgaudet
          - name: dcflash-data
            hostPath:
              path: /rdma/flash/AI2ES/data
          restartPolicy: OnFailure    ##  Restart Policy in case container failed
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: concat-hrrr-12
  namespace: arnoldas
  labels:
    app: concat-hrrr-12
spec:
  schedule: "30 13 * * *"            ## Defined schedule using the *nix style cron syntax
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: concat-hrrr-12
        spec:
          containers:
          - name: concat-hrrr-12
            image:  akurbanovas/cron_lg:0.4
            volumeMounts:
            - name: dcflash-storage-lg
              mountPath: /home/lgaudet
            - name: dcflash-data
              mountPath: /home/lgaudet/model-data
            command: ["/bin/bash"]
            args: ["-c", "/opt/conda/envs/data_pipeline/bin/python /home/lgaudet/AI2ES/Notebooks/single_file_pipeline/concat_files_fix_precip.py -m 'hrrr' -p 'wrfsfc' -d $(date +%Y%m%d) -i '12'"]
          volumes:
          - name: dcflash-storage-lg
            hostPath:
              path: /rdma/flash/hulk/raid/lgaudet
          - name: dcflash-data
            hostPath:
              path: /rdma/flash/AI2ES/data
          restartPolicy: OnFailure    ##  Restart Policy in case container failed
---