apiVersion: apps/v1
kind: Deployment
metadata:
  name: cron-ae
  labels:
    app: cron-ae
spec:
#  nodeName: lambda
  selector:
    matchLabels:
      app: cron-ae
  template:
    metadata:
      labels:
        app: cron-ae
    spec:
      securityContext:
        runAsUser: 22085
        runAsGroup: 22082
      containers:
        - name: cron-ae
          image:  akurbanovas/cron_lg:aevans
          volumeMounts:
          - name: dcflash-storage-lg
            mountPath: /home/lgaudet
          - name: dcflash-data
            mountPath: /home/lgaudet/model-data
          - name: home
            mountPath: /home/aevans
          command: ["/bin/sh"]
          args: ["-c", "jupyter lab --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX} /home/lgaudet"]
#          resources:
#            limits:
#              nvidia.com/gpu: 1
          ports:
            - containerPort: 8888
      volumes:
      - name: dcflash-storage-lg
        hostPath:
          path: /rdma/flash/hulk/raid/lgaudet
      - name: dcflash-data
        hostPath:
          path: /rdma/flash/AI2ES/data
      - name: home
        hostPath:
          path: /home/aevans
---
# apiVersion: v1
# kind: Service
# metadata:
#   name: cron-lg
#   labels:
#     app: cron-lg
# spec:
#   selector:
#     app: cron-lg
#   type: NodePort
#   ports:
#     - targetPort: 8888
#       nodePort: 30008
#       port: 8888
#       name: http
#       protocol: TCP