apiVersion: rbacmanager.reactiveops.io/v1beta1
kind: RBACDefinition
metadata:
  name: csutter-access
rbacBindings:
  - name: csutter
    subjects:
      - kind: User
        name: csutter
    roleBindings:
      - namespace: csutter
        clusterRole: edit
      - namespace: default
        clusterRole: view
      - namespace: ai2es
        clusterRole: edit
      - namespace: xcite
        clusterRole: view