apiVersion: apps/v1
kind: Deployment
metadata:
  name: deepak-jl
  labels:
    app: deepak-jl
spec:
#  nodeName: lambda
  selector:
    matchLabels:
      app: deepak-jl
  template:
    metadata:
      labels:
        app: deepak-jl
    spec:
      containers:
        - name: deepak-jl
          image: akurbanovas/coe:emily
          volumeMounts:
          - name: hulk
            mountPath: /home/dkumar
          command: ["/bin/sh"]
          args: ["-c", "jupyter lab --ip=0.0.0.0 --no-browser --allow-root --port=8888 --NotebookApp.allow_origin='*' --NotebookApp.base_url=${NB_PREFIX}/deepak /home/dkumar"]
          imagePullPolicy: Always
#          resources:
#            limits:
#              nvidia.com/gpu: 2
          ports:
            - containerPort: 8888
#            - containerPort: 8686
#            - containerPort: 8787
      volumes:
      - name: hulk
        hostPath:
          path: /rdma/hulk/coe/dkumar/
---
