apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod
  namespace: default
spec:
  containers:
    - name: cuda-test
      image: akurbanovas/kara_kce:v5
      command: 
      - nvidia-smi
#      resources:
#        limits:
#          nvidia.com/gpu: 1
  nodeName: dgx-a100