apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: objclouds
  name: objclouds
  annotations:
      date: "+%H:%M:%S %d/%m/%y"
spec:
  containers:
  - name: objclouds
    image: akurbanovas/edd_kube
    ports:
    - containerPort: 8888
    workingDir: /raid
    #command: ['/bin/bash', '-c', 'jupyter lab']
    #args: ["/raid/arnold/clouds_detection/start.sh"]
    securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 0
    volumeMounts:
    - name: raid
      mountPath: /raid
      readOnly: false
    resources:
      limits:
        nvidia.com/gpu: "1"
  volumes:
    - name: raid
      hostPath:
        path: /raid
  dnsPolicy: ClusterFirst
  #terminationGracePeriodSeconds: 120
  restartPolicy: Always
