apiVersion: apps/v1
kind: Deployment
metadata:
  name: meso-backup
  labels:
    app: meso-backup
  namespace: arnoldas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: meso-backup
  template:
    metadata:
      labels:
        app: meso-backup 
    spec:
      containers:
        - name: meso-backup
          image: akurbanovas/meso_web:v2
          ports:
            - containerPort: 80
          #command: ["/bin/sh"]
          #args: ["-c", "npm start -p 80"]