#working version, completes right away run using kubectl create -f obj_clouds.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: clouds
  name: clouds
spec:
  containers:
  - args:
    - nvidia-smi
    image: akurbanovas/od_tf1:v1
    name: clouds
    ports:
    - containerPort: 8890
    resources:
      limits:
        nvidia.com/gpu: "1"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
