#working version, completes right away run using kubectl create -f obj_clouds.yaml
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: clouds
  name: clouds
spec:
  containers:
  - args:
    - nvidia-smi
    image: akurbanovas/od_tf1:v1
    name: clouds
    ports:
    - containerPort: 8890
    resources:
      limits:
        nvidia.com/gpu: "1"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
—
#working with hostpath and continues running after starting log prints app is running
apiVersion: v1
kind: Pod
metadata:
  name: clouds
spec:
  containers:
  - args:
    - nvidia-smi
    image: akurbanovas/od_tf1:v1
    name: clouds
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    volumeMounts:
    - name: raid
      mountPath: /raid
    ports:
    - containerPort: 8890
    resources:
      limits:
        nvidia.com/gpu: "1"
  volumes:
    - name: raid
      hostPath:
        path: /raid
  dnsPolicy: ClusterFirst
  restartPolicy: Never
—
#working execute python file with env set in dockerfile 
apiVersion: v1
kind: Pod
metadata:
  name: clouds
spec:
  containers:
  - args:
    - nvidia-smi
    image: akurbanovas/od_tf1:v1
    name: clouds
    command: ['python', '/raid/arnold/clouds_detection/modelsV2/research/object_detection/legacy/train.py']
    volumeMounts:
    - name: raid
      mountPath: /raid
      readOnly: false
    ports:
    - containerPort: 8890
    resources:
      limits:
        nvidia.com/gpu: "1"
  volumes:
    - name: raid
      hostPath:
        path: /raid
  dnsPolicy: ClusterFirst
  restartPolicy: Never
—
#set workdir, run python code on start with arguments
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: gpu-job
  name: gpu-job
spec:
  containers:
  - args:
    - python
    - train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config
    image: akurbanovas/od_tf1:v1
    name: gpu-job
    volumeMounts:
    - name: raid
      mountPath: /raid
      readOnly: false
    workingDir: /raid/arnold/clouds_detection/modelsV2/research/object_detection/legacy/
    resources:
      limits:
        nvidia.com/gpu: "1"
  volumes:
    - name: raid
      hostPath:
        path: /raid
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
