kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: jupyter-user-binding
  namespace: vanessa
subjects:
- kind: User
  name:	vanessa
  apiGroup: ""
roleRef:
  kind: Role
  name:	jupyter-user
  apiGroup: ""
