apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-nick-php
  namespace: arnoldas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-nick-php
  template:
    metadata:
      labels:
        app: web-nick-php
    spec:
      containers:
      - name: web-nick-php
        image: php:8.0-apache
        volumeMounts:
        - name: hulk
          mountPath: /var/www/html
        #command: ["/bin/bash"]
        #args: ["-c", "http-server /home/coe/web -p 8080 -o /coeweather "]
        ports:
          - containerPort: 80
      volumes:
      - name: hulk
        hostPath:
          path: /rdma/hulk/coe/web/coeweather/dhses
---
#apiVersion: v1
#kind: Service
#metadata:
#  name: web-nick
#  namespace: arnoldas
#spec:
#  type: NodePort
#  selector:
#    app: web-nick
#  ports:
#  - port: 8080
#    targetPort: 8080
#    nodePort: 31080
#    protocol: TCP
#  selector:
#    app: web-nick