apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-nick
  namespace: arnoldas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-nick
  template:
    metadata:
      labels:
        app: web-nick
    spec:
      containers:
      - name: web-nick
        image: akurbanovas/http-server:php
        volumeMounts:
        - name: hulk
          mountPath: /home/coe/web
        command: ["/bin/bash"]
        args: ["-c", "http-server /home/coe/web -p 8080 -o /coeweather "]
        ports:
          - containerPort: 8080
      volumes:
      - name: hulk
        hostPath:
          path: /rdma/hulk/coe/web
---
apiVersion: v1
kind: Service
metadata:
  name: web-nick
  namespace: arnoldas
spec:
  type: NodePort
  selector:
    app: web-nick
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31080
    protocol: TCP
  selector:
    app: web-nick