apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devtron-ingress
  namespace: devtroncd
  uid: fbed0515-3e20-4d63-bc0d-c0660836951c
  resourceVersion: '24272243'
  generation: 1
  creationTimestamp: '2024-10-02T18:24:35Z'
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"kubernetes.io/ingress.class":"nginx","nginx.ingress.kubernetes.io/rewrite-target":"/$2"},"name":"devtron-ingress","namespace":"devtroncd"},"spec":{"rules":[{"host":"swrcc02.asrc.albany.edu","http":{"paths":[{"backend":{"service":{"name":"devtron-service","port":{"number":8080}}},"path":"/","pathType":"Prefix"}]}},{"host":"swrcc01.asrc.albany.edu","http":{"paths":[{"backend":{"service":{"name":"devtron-service","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}},{"host":"swrcc03.asrc.albany.edu","http":{"paths":[{"backend":{"service":{"name":"devtron-service","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}],"tls":[{"hosts":["swrcc01.asrc.albany.edu","swrcc02.asrc.albany.edu","swrcc03.asrc.albany.edu"],"secretName":"hello-kubernetes-tls"}]}}
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  managedFields:
    - manager: kubectl-client-side-apply
      operation: Update
      apiVersion: networking.k8s.io/v1
      time: '2024-10-02T18:24:35Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:kubectl.kubernetes.io/last-applied-configuration: {}
            f:kubernetes.io/ingress.class: {}
            f:nginx.ingress.kubernetes.io/rewrite-target: {}
        f:spec:
          f:rules: {}
          f:tls: {}
    - manager: nginx-ingress-controller
      operation: Update
      apiVersion: networking.k8s.io/v1
      time: '2024-10-02T18:25:14Z'
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:loadBalancer:
            f:ingress: {}
      subresource: status
  selfLink: /apis/networking.k8s.io/v1/namespaces/devtroncd/ingresses/devtron-ingress
status:
  loadBalancer:
    ingress:
      - ip: 10.114.68.153
      - ip: 10.114.68.156
      - ip: 10.114.68.157
spec:
  tls:
    - hosts:
        - swrcc01.asrc.albany.edu
        - swrcc02.asrc.albany.edu
        - swrcc03.asrc.albany.edu
      secretName: hello-kubernetes-tls
  rules:
    - host: swrcc02.asrc.albany.edu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devtron-service
                port:
                  number: 80
    - host: swrcc01.asrc.albany.edu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devtron-service
                port:
                  number: 80
    - host: swrcc03.asrc.albany.edu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: devtron-service
                port:
                  number: 80
