apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: coder-cert
spec:
  secretName: coder-tls
  renewBefore: 240h
  duration: 2160h
  commonName: coder.xcitelab.org
  dnsNames:
  - coder.xcitelab.org
  issuerRef:
    name: letsencrypt-prod-xcitedb
    kind: ClusterIssuer