apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-dcflash
spec:
  secretName: secret-tls-dcflash
  renewBefore: 240h
  duration: 2160h
  commonName: dcflash.asrc.albany.edu
  dnsNames:
  - dcflash.asrc.albany.edu
  issuerRef:
    name: letsencrypt-prod-xcitedb
    kind: ClusterIssuer