apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert
spec:
  secretName: grafana-cert
  renewBefore: 240h
  duration: 2160h
  commonName: xcite-grafana.asrc.albany.edu
  dnsNames:
  - xcite-grafana.asrc.albany.edu
  issuerRef:
    name: letsencrypt-prod-xcitedb
    kind: ClusterIssuer