apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test-server
  namespace: arnoldas
spec:
  secretName: test-server-tls
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
  - "xcitelab.org"
  - "xcitelab"
  issuerRef:
    name: test-ca-issuer
---
